{
 "title": "Spacemesh Metrics",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "percentile",
    "query": "0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,0.95,0.99"
   },
   { "name": "sign", "query": "pos, neg" }
  ]
 },
 "panels": [
  {
   "title": "Sync Status",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "spacemesh_syncer_sync_state{state=\"synced\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Synced Layer",
   "type": "stat",
   "gridPos": { "h": 14, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "spacemesh_syncer_layer", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 4, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "spacemesh_p2p_peers_per_protocol",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Activation Publish On Time",
   "type": "status-history",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 8 },
   "targets": [
    {
     "expr": "spacemesh_activation_publish_window_seconds_count{condition=\"ontime\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ATX Sync Status",
   "type": "status-history",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 15 },
   "targets": [
    {
     "expr": "spacemesh_syncer_sync_state{state=\"atx_synced\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Activation Post Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "spacemesh_activation_post_duration / 1000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Message Latencies Atx",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": " sum by(le,instance) (rate(spacemesh_message_latency_seconds_count{protocol=\"ax1\"}[5m]))",
     "legendFormat": "Activation-{{instance}}"
    }
   ]
  },
  {
   "title": "Activation POET pow duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "spacemesh_activation_poet_pow_duration / 1000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Message Latencies Beacon",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(spacemesh_message_latency_seconds_count{protocol=\"b1\", sign=\"$sign\"}[5m])) by (le,type,instance)",
     "legendFormat": "{{type}}{{instance}}"
    }
   ]
  },
  {
   "title": "Message Latencies Hare",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(le, type, instance) (rate(spacemesh_message_latency_seconds_count{protocol=\"hr1\", sign=\"$sign\"}[5m]))",
     "legendFormat": "{{type}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Message Latencies",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": " sum by(le,instance) (rate(spacemesh_message_latency_seconds_count{protocol=\"b1\", sign=\"$sign\"}[5m]))",
     "legendFormat": "b1-{{instance}}"
    },
    {
     "expr": "sum by(le,instance) (rate(spacemesh_message_latency_seconds_count{protocol=\"hr1\",sign=\"$sign\"}[5m]))",
     "legendFormat": "hr1-{{instance}}"
    },
    {
     "expr": "sum by(le,instance) (rate(spacemesh_message_latency_seconds_count{protocol=\"pp1\",sign=\"$sign\"}[5m]))",
     "legendFormat": "pp1-{{instance}}"
    }
   ]
  }
 ]
}