version: "3"
services:
  miner:
    build: .
    image: "spacemesh"
    privileged: true
    volumes:
      - ./node_data:/container/go-spacemesh/build/node_data
      - ./data:/container/go-spacemesh/build/post_data
    environment:
      - SMESHING_COINBASE_ADDRESS=sm1qqqqqq...
      - FILE_SIZE=34359738368
      - NUMUNITS=4
    restart: unless-stopped
    network_mode: bridge
