version: '3.7'
services:
  spacemesh:
    image: spacemesh
    build:
      context: .
    networks:
      - sm_network
    ports:
      - "80:80"
    privileged: true
    volumes:
      - ./node_data:/app/go-spacemesh/node_data
      - ${POSTDATA_DIR:-./data}:/app/go-spacemesh/post_data
    environment:
      - SMESHING_COINBASE_ADDRESS=${SMESHING_COINBASE_ADDRESS:?please make sure to set your SMESHING_COINBASE_ADDRESS environment variable in the .env file}
      - FILE_SIZE=${FILE_SIZE:?please make sure to set your FILE_SIZE environment variable in the .env file}
      - NUMUNITS=${NUMUNITS:?please make sure to set your NUMUNITS environment variable in the .env file}
    restart: unless-stopped

  # 有几个添加几个
  # service1:
  #   image: spacemesh-service
  #   networks:
  #     - sm_network
  #   depends_on:
  #     - spacemesh
  #   privileged: true
  #   volumes:
  #     # 第一个service的数据目录
  #     - /root/postdata1:/app/go-spacemesh/post_data
  #   environment:
  #     - THREADS=8
  #     - NONCES=288
  #   restart: unless-stopped

  # service2:
  #   image: spacemesh-service
  #   networks:
  #     - sm_network
  #   depends_on:
  #     - spacemesh
  #   privileged: true
  #   volumes:
  #     # 第2个service的数据目录
  #     - /root/postdata2:/app/go-spacemesh/post_data
  #   environment:
  #     - THREADS=8
  #     - NONCES=288
  #   restart: unless-stopped
  

networks:
  sm_network:

