version: '3.7'
services:
  spacemesh:
    build:
      context: .
      args:
        VERSION: 'v1.1.1'

    ports:
      - '7513:7513'
    privileged: true
    volumes:
      - ./node_data:/container/go-spacemesh/build/node_data
      - ./data:/container/go-spacemesh/build/post_data
    environment:
      - SMESHING_COINBASE_ADDRESS=${SMESHING_COINBASE_ADDRESS:?please make sure to set your SMESHING_COINBASE_ADDRESS environment variable in the .env file}
      - FILE_SIZE=${FILE_SIZE:?please make sure to set your FILE_SIZE environment variable in the .env file}
      - NUMUNITS=${NUMUNITS:?please make sure to set your NUMUNITS environment variable in the .env file}
    restart: unless-stopped
    network_mode: bridge
